import LightboxGallery from '../components/LightboxGallery';
import { faGithub } from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import HeadComponent from '../components/HeadComponent';
import { useTranslation } from '../hooks/useTranslation';
import { useLanguageContext } from '../context/LanguageContext';

const MailXaminerHtmlReport = () => {
    const { t, language, isLoading } = useTranslation('mailxaminer-html-report');
    const { language: contextLanguage } = useLanguageContext();

    if (isLoading) {
        return <div>Loading...</div>;
    }

    const slides = [
        { src: '/images/MailXaminer/UI.jpg', title: t('gallery.slide1.title', 'MailXaminer HTML Report Graphical Interface'), description: t('gallery.slide1.description', 'The program shows the folder structure before generating the report') },
        { src: '/images/MailXaminer/Strut-orig-2.jpg', title: t('gallery.slide2.title', 'Original Structure'), description: t('gallery.slide2.description', 'Folder structure generated by MailXaminer, the program will recognize the structure and generate the appropriate links') },
        { src: '/images/MailXaminer/layout.jpg', title: t('gallery.slide3.title', 'Report Interface'), description: t('gallery.slide3.description', 'Report graphical interface, on the left folder selection. At the top emails, at the bottom the selected email.') },
        { src: '/images/MailXaminer/layout filtered.jpg', title: t('gallery.slide4.title', 'Report Interface with Filters'), description: t('gallery.slide4.description', '') },
    ];

    const pageUrl = language === 'en' 
        ? 'https://alexcortinovis.tech/en/mailxaminer-html-report'
        : 'https://alexcortinovis.tech/mailxaminer-html-report';

    return (
        <main className='main-section' style={{ maxWidth: 1080, margin: '0 auto' }}>
            <HeadComponent
                title={`${t('title', 'MailXaminer HTML Report')} - Alex Cortinovis`}
                description={t('description', 'The application allows you to generate an index HTML file to view all emails exported in HTML from the forensic software MailXaminer.')}
                url={pageUrl}
                image={slides[0].src}
            />
            <div style={{ padding: '1rem 2rem' }}>
                <h1>{t('title', 'MailXaminer HTML Report')}</h1>
                <p>
                    {t('content.intro', 'Starting from an HTML report generated by the forensic software')}&nbsp;<a href="https://www.mailxaminer.com/" target="_blank" rel="noopener noreferrer">MailXaminer</a>, {t('content.generate', 'allows you to generate an index HTML file.')} <br />
                    {t('content.description', 'This file allows you to view in a web page, divided into 3 sections, all the emails in the generated report.')} <br />
                    {t('content.layout', 'On the left the subfolders, on the right at the top the list of emails that the selected folder contains, and at the bottom the selected email.')} <br />
                    {t('content.filters', 'Additionally, it is possible to apply filters to the email list.')} <br />
                </p>
                <div style={{ margin: '2rem 0', display: 'flex', justifyContent: 'center', gap: '1rem' }}>
                    <a className="button" href="https://github.com/walker93/Mailxaminer-HTML-Report-Index" target="_blank" rel="noopener noreferrer">
                        <FontAwesomeIcon icon={faGithub} style={{ marginRight: 8 }} />{t('sourceCode', 'View source code on GitHub')}
                    </a>
                </div>
                <LightboxGallery slides={slides} />
            </div>
        </main>
    );
};

export default MailXaminerHtmlReport;
