import LightboxGallery from '../components/LightboxGallery';
import { faGithub } from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import HeadComponent from '../components/HeadComponent';
import { useTranslation } from '../hooks/useTranslation';
import { useLanguageContext } from '../context/LanguageContext';

const TwrpToUfed = () => {
    const { t, language, isLoading } = useTranslation('twrp-to-ufed');
    const { language: contextLanguage } = useLanguageContext();

    if (isLoading) {
        return <div>Loading...</div>;
    }

    const slides = [
        { src: '/images/TWRP-to-UFED/prompt command.jpg', title: t('gallery.slide1.title', 'Prompt with Command'), description: t('gallery.slide1.description', '') },
        { src: '/images/TWRP-to-UFED/comando terminato.jpg', title: t('gallery.slide2.title', 'Command Completed'), description: t('gallery.slide2.description', '') },
        { src: '/images/TWRP-to-UFED/twrp originale.jpg', title: t('gallery.slide3.title', 'Original Structure Generated by TWRP Backup'), description: t('gallery.slide3.description', '') },
        { src: '/images/TWRP-to-UFED/Struttura finale2.jpg', title: t('gallery.slide4.title', 'Folder Structure at Completion'), description: t('gallery.slide4.description', 'The folder structure when the command is completed contains a "UFED" folder to import into the program') },
    ];

    const pageUrl = language === 'en' 
        ? 'https://alexcortinovis.tech/en/twrp-to-ufed'
        : 'https://alexcortinovis.tech/twrp-to-ufed';

    return (
        <main className='main-section' style={{ maxWidth: 1080, margin: '0 auto' }}>
            <HeadComponent
                title={`${t('title', 'TWRP to UFED')} - Alex Cortinovis`}
                description={t('description', 'The application is able to convert a Nandroid Backup generated with the well-known custom recovery TWRP into a format importable in the Cellebrite UFED Physical Analyzer suite.')}
                url={pageUrl}
                image={slides[0].src}
            />
            <div style={{ padding: '1rem 2rem' }}>
                <h1>{t('title', 'TWRP to UFED')}</h1>
                <p>
                    {t('content.intro', 'The application is able to convert a Nandroid Backup generated with the well-known custom recovery')}&nbsp;<a href="https://twrp.me/" target="_blank" rel="noopener noreferrer">TWRP</a>&nbsp;{t('content.format', 'into a format importable in the Cellebrite UFED Physical Analyzer suite.')} <br />
                    {t('content.usecase', 'This tool is useful when it is not possible to perform the physical acquisition of an Android mobile device, but it is possible to install or run the custom recovery and perform the backup on SD or external OTG support.')} <br />
                    {t('content.usage', 'Execution is very simple, without a graphical interface, you just need to indicate the folder containing the backup when running from Prompt or Powershell.')} <br />
                </p>
                <div style={{ margin: '2rem 0', display: 'flex', justifyContent: 'center', gap: '1rem' }}>
                    <a className="button" href="https://github.com/walker93/TWRP-to-UFED" target="_blank" rel="noopener noreferrer">
                        <FontAwesomeIcon icon={faGithub} style={{ marginRight: 8 }} />{t('sourceCode', 'View source code on GitHub')}
                    </a>
                </div>
                <LightboxGallery slides={slides} />
            </div>
        </main>
    );
};

export default TwrpToUfed;
